# Generated by Django 5.2.10 on 2026-01-17 05:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_сomplaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сomplaint',
            new_name='Complaint',
        ),
    ]
