# Generated by Django 5.2.10 on 2026-01-18 03:02

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.owners_phonenumber:
            continue
        try:
            phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except phonenumbers.NumberParseException:
            continue
        if not phonenumbers.is_valid_number(phone):
            continue
        flat.owner_pure_phone = phonenumbers.format_number(
            phone,
            phonenumbers.PhoneNumberFormat.E164
        )
        flat.save(update_fields=['owner_pure_phone'])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone)
    ]
