# Generated by Django 5.2.10 on 2026-01-18 04:30

from django.db import migrations


def link_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
            )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20260118_1508'),
    ]

    operations = [
        migrations.RunPython(link_owners_and_flats)
    ]
