# Generated by Django 5.2.10 on 2026-01-29 12:19

from django.db import migrations


def fix_owner_lookup(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator(chunk_size=2000):
        if not flat.owner_pure_phone:
            continue
        owner, _ = Owner.objects.get_or_create(
            owner_pure_phone=flat.owner_pure_phone,
            defaults={
                'full_name': flat.owner,
            }
        )

    owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20260118_1530'),
    ]

    operations = [
    ]
