# Generated by Django 5.2.10 on 2026-01-31 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_flat_owners_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
